# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.

from snakemake.utils import min_version


min_version("6.3.0")


configfile: "config/config.yaml"


pepfile: config["pepfile"]


report: "report/workflow.rst"


include: "rules/common.smk"
include: "rules/ref.smk"
include: "rules/external_arg_tools.smk"
include: "rules/report.smk"


rule all:
    input:
        "results/OSD14-ARG-Report.zip"
