# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.

from snakemake.utils import min_version


min_version("6.3.0")

configfile: "config/config.yaml"

pepfile: config["pepfile"]

report: "report/workflow.rst"

# Allow users to fix the underlying OS via singularity.
singularity: "docker://continuumio/miniconda3"


include: "rules/common.smk"
include: "rules/other.smk"
include: "rules/ref.smk"
include: "rules/external_arg_tools.smk"

rule all:
    input:
        # The first rule should define the default target files
        # Subsequent target rules can be specified below. They should start with all_*.

